### ISSUE TITLE
Pitch and Roll are correlated

### ISSUE THREAD

**Issue by coolkuba** [michkrom/stm32f3discovery#1]
I was testing rotation along each axis and when I test Pitch also Roll is changing. Strangely enough if I test Roll Pitch is oscillating around zero. It is very strange because accelerometer seem to return correct values

The pitch test which is wrong (not zero roll value)
ypr[0]=-28.88  
ypr[1]=-31.022  
ypr[2]=-16.18  
acc data:
a[0]=5.73
a[1]=-0.17
a[2]=9.43

When I perform only roll test results are fine:
ypr[0]=-35.66  
ypr[1]=-0.57  
ypr[2]=30.98  
acc data:
a[0]=0.02  
a[1]=6.47  
a[2]=8.68   

and yaw also fine:
ypr[0]=-89.38  
ypr[1]=0.83 
ypr[2]=0.83 
acc data:
a[0]=-0.16  
a[1]=0.07  
a[2]=11.01

**Comment by michkrom** [comment]
I may have mixed euler with aerospace ypr sequence - depending on reference
frame and order of rotation application they may be correlated (think what
roll means then pitch goes to 90deg?). Did not work on that board recently.
See this  https://answers.launchpad.net/freeimu/+question/150323

One experiment would be to zero out gyro and mag (ie pass 0,0,0 to ahr
routines) and see that they return . Another is just to use the conv
routines to convert gravity vector  (acc readout) to object (board)
orientation.

On Sat, Jan 11, 2014 at 5:38 AM, coolkuba notifications@github.com wrote:

> I was testing rotation along each axis and when I test Pitch also Roll is
> changing. Strangely enough if I test Roll Pitch is oscillating around zero.
> It is very strange because accelerometer seem to return correct values
> 
> The pitch test which is wrong (not zero roll value)
> ypr[0]=-28.88
> 
> ypr[1]=-31.022
> 
> ypr[2]=-16.18
> 
> acc data:
> a[0]=5.73
> a[1]=-0.17
> a[2]=9.43
> 
> When I perform only roll test results are fine:
> ypr[0]=-35.66
> 
> ypr[1]=-0.57
> 
> ypr[2]=30.98
> 
> acc data:
> a[0]=0.02
> 
> a[1]=6.47
> 
> a[2]=8.68
> 
> and yaw also fine:
> ypr[0]=-89.38
> 
> ypr[1]=0.83
> ypr[2]=0.83
> acc data:
> a[0]=-0.16
> 
> a[1]=0.07
> 
> a[2]=11.01
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/michkrom/stm32f3discovery/issues/1
> .

## 

Michal, Iza, Kai & Nell

**Comment by coolkuba** [comment]
I tried to pass fix value for magnetometer (1,1,1) because 0 caused error and (0,0,0) for gyro and still problem exists. Still I tested only fullAHRS routine. Did You have similar problem?

**Comment by michkrom** [comment]
You can suppress gyro with 0,0,0, mag has to have reasonable value.
Suppressing gyro would just make slower response but stready state result
should be the same.

Just tried FreeIMU on my Flip MWC board (arduino) and it does not couple
pitch/roll so you're right that it should not.

Perhaps I will port the FreeIMU to STM32D3 as it seems to work fine on
arduino...no idea why the original
Madgwickhttp://uk.linkedin.com/pub/sebastian-madgwick/21/980/a82alg
is broken here...

On Mon, Jan 13, 2014 at 11:58 AM, coolkuba notifications@github.com wrote:

> I tried to pass fix value for magnetometer (1,1,1) because 0 caused error
> and (0,0,0) for gyro and still problem exists. Still I tested only fullAHRS
> routine. Did You have similar problem?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/michkrom/stm32f3discovery/issues/1#issuecomment-32204921
> .

## 

Michal, Iza, Kai & Nell

**Comment by michkrom** [comment]
hey!

the imuQuaternionToYawPitchRoll was using aerospace sequence of rotation.
changed it to earth referenced as it was intended now works as expected

pull from github

later,
michal

On Tue, Jan 14, 2014 at 10:59 PM, Michal Krombholz krombholz@gmail.comwrote:

> You can suppress gyro with 0,0,0, mag has to have reasonable value.
> Suppressing gyro would just make slower response but stready state result
> should be the same.
> 
> Just tried FreeIMU on my Flip MWC board (arduino) and it does not couple
> pitch/roll so you're right that it should not.
> 
> Perhaps I will port the FreeIMU to STM32D3 as it seems to work fine on
> arduino...no idea why the original Madgwickhttp://uk.linkedin.com/pub/sebastian-madgwick/21/980/a82alg is broken here...
> 
> On Mon, Jan 13, 2014 at 11:58 AM, coolkuba notifications@github.comwrote:
> 
> > I tried to pass fix value for magnetometer (1,1,1) because 0 caused error
> > and (0,0,0) for gyro and still problem exists. Still I tested only fullAHRS
> > routine. Did You have similar problem?
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/michkrom/stm32f3discovery/issues/1#issuecomment-32204921
> > .
> 
> ## 
> 
> Michal, Iza, Kai & Nell

## 

Michal, Iza, Kai & Nell

**Comment by coolkuba** [comment]
Hello,
Thank You very much!!! I will check if this solves my problem tomorrow.
Kuba

**Comment by coolkuba** [comment]
Hello,
I just check it and it is working correctly. Nice project by the way!
Kuba
